# After installation SSH into the server and type:
# sudo cat /var/lib/jenkins/secrets/initialAdminPassword

# This template was created using these instructions:
# https://d1.awsstatic.com/Projects/P5505030/aws-project_Jenkins-build-server.pdf
Parameters:
  NameOfService:
    Description: Jenkins Master
    Type: String
    Default: jenkins-master
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access into the server
    Type: String
    Default: aws-eb
Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-003f19e0e687de1cd
    us-west-1:
      AMI: ami-bf5540df
    eu-west-1:
      AMI: ami-3bfab942
    ap-southeast-1:
      AMI: ami-e2adf99e
    ap-southeast-2:
      AMI: ami-43874721
Resources:
  # Create an elastic IP so that the ip address doesn't change.
  IPAddress:
    Type: AWS::EC2::EIP
    # Add the Elastic IP to the jenkins instance
  IPAssoc:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref 'JenkinsInstance'
      EIP: !Ref 'IPAddress'    
  JenkinsInstance:
    Type: AWS::EC2::Instance
    Properties:    
      InstanceType: t2.micro
      ImageId:
        Fn::FindInMap:
          - RegionMap
          - !Ref AWS::Region
          - AMI
      SecurityGroupIds:
        - !Ref JenkinsSecurityGroup
      Tags:
        - Key: Name
          Value: !Ref NameOfService
      KeyName: !Ref KeyName
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          ######################################################################
          # Time Zone
          ######################################################################          
          
          # Changes the timezone so we can see relevant the log times.
          sudo timedatectl set-timezone America/New_York          

          ######################################################################
          # Docker
          # https://linuxize.com/post/how-to-install-and-use-docker-on-debian-10/
          ######################################################################
                    
          # Uninstall old versions
          sudo apt remove docker docker-engine docker.io containerd runc || true

          # Update packages
          sudo apt update

          # Install packages to allow apt to use a repository over HTTPS:
          echo Y |
              sudo apt-get install \
              apt-transport-https \
              ca-certificates \
              curl \
              gnupg-agent \
              software-properties-common

          # Add docker official GPG keys
          curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -

          # Set up stable repository
          sudo add-apt-repository \
            "deb [arch=amd64] https://download.docker.com/linux/debian \
            $(lsb_release -cs) \
            stable"

          # Update packages
          sudo apt-get update

          # Install latest version off Docker Engine
          echo Y | sudo apt-get install docker-ce docker-ce-cli containerd.io

          ######################################################################
          # Docker Compose
          # https://docs.docker.com/compose/install/
          ######################################################################

          # Download
          sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" \
          -o /usr/local/bin/docker-compose

          # Add executable permissions
          sudo chmod +x /usr/local/bin/docker-compose

          # Create Symlink
          sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

          ######################################################################
          # Utils
          ######################################################################

          # Monitoring
          sudo apt install htop

          ######################################################################
          # Swap Memory
          ######################################################################

          # Create the swapfile 128x32 = 4GB          
          sudo dd if=/dev/zero of=/swapfile bs=128M count=32

          # Set permissions
          sudo chmod 600 /swapfile

          # Make the swap file
          sudo mkswap /swapfile

          # mount the swap file
          sudo swapon /swapfile

          # idk what this is
          sudo swapon -s

          # Set the swap memory every time OS boots up.
          sudo su -c "echo /swapfile swap swap defaults 0 0 >> /etc/fstab"      

          ######################################################################
          # System Access - logged in as admin user
          ######################################################################          
          
          # admin - Create the ssh keys
          ssh-keygen -t rsa -C "[jenkins]jenkins-master" -f ~/.ssh/id_rsa -q -P ""

          # admin - Add user to docker to prevent having to sudo the Docker commands.
          sudo usermod -aG docker admin
                    
          # admin - add jenkins user to various groups
          sudo usermod -aG docker jenkins
          sudo usermod -aG sudo jenkins

          # admin - log as jenkins
          sudo su jenkins

          # jenkins - log into /var/lib/jenkins/
          cd ~

          # jenkins -  Create the ssh keys for the jenkins user
          ssh-keygen -t rsa -C "[jenkins]jenkins-master" -f ~/.ssh/id_rsa -q -P ""
          
          # jenins - Go back to the admin shell
          exit
  JenkinsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Open Ports 22 and 80
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
Outputs:
  Website:
    Description: The Public DNS for the EC2 Instance
    Value: !Sub "http://${JenkinsInstance.PublicDnsName}:8080"
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref 'JenkinsInstance'
  InstanceIPAddress:
    Description: IP address of the newly created EC2 instance
    Value: !Ref 'IPAddress'    
