# After installation SSH into the server and type:
# sudo cat /var/lib/jenkins/secrets/initialAdminPassword

# This template was created using these instructions:
# https://d1.awsstatic.com/Projects/P5505030/aws-project_Jenkins-build-server.pdf
Parameters:
  NameOfService:
    Description: Jenkins server
    Type: String
    Default: Jenkins
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access into the server
    Type: String
    Default: aws-eb
Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-003f19e0e687de1cd
    us-west-1:
      AMI: ami-bf5540df
    eu-west-1:
      AMI: ami-3bfab942
    ap-southeast-1:
      AMI: ami-e2adf99e
    ap-southeast-2:
      AMI: ami-43874721
Resources:
  JenkinsInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.nano
      ImageId:
        Fn::FindInMap:
          - RegionMap
          - !Ref AWS::Region
          - AMI
      SecurityGroupIds:
        - !Ref JenkinsSecurityGroup
      Tags:
        - Key: Name
          Value: !Ref NameOfService
      KeyName: !Ref KeyName
      UserData:
        "Fn::Base64": !Sub |
          #!/bin/bash -xe
          ######################################################################
          # Jenkins - Debian9
          ######################################################################

          # Update packages
          sudo apt update

          # Install OpenJDK11
          echo Y | sudo apt install default-jdk

          # Import Repository keys
          wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -

          # Add Jenkins to the repository
          sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'

          # Update packages
          sudo apt update

          # Install Jenkins
          echo Y | sudo apt install jenkins

          # Start Jenkins
          sudo systemctl enable --now jenkins

          ######################################################################
          # Docker - Debian9
          # https://linuxize.com/post/how-to-install-and-use-docker-on-debian-10/
          ######################################################################
                    
          # Uninstall old versions
          sudo apt remove docker docker-engine docker.io containerd runc || true

          # Update packages
          sudo apt update

          # Install packages to allow apt to use a repository over HTTPS:
          echo Y |
              sudo apt-get install \
              apt-transport-https \
              ca-certificates \
              curl \
              gnupg-agent \
              software-properties-common

          # Add docker official GPG keys
          curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -

          # Set up stable repository
          sudo add-apt-repository \
            "deb [arch=amd64] https://download.docker.com/linux/debian \
            $(lsb_release -cs) \
            stable"

          # Update packages
          sudo apt-get update

          # Install latest version off Docker Engine
          echo Y | sudo apt-get install docker-ce docker-ce-cli containerd.io

          # Add user to docker to prevent having to sudo the Docker commands.  
          sudo usermod -aG docker $USER
          sudo usermod -aG docker jenkins

          ######################################################################
          # Docker Compose
          # https://docs.docker.com/compose/install/
          ######################################################################

          # Download
          sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" \
          -o /usr/local/bin/docker-compose

          # Add executable permissions
          sudo chmod +x /usr/local/bin/docker-compose

          # Create Symlink
          sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

          ######################################################################
          # Utils
          ######################################################################

          # Monitoring
          apt install htop

  JenkinsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Open Ports 22 and 80
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
Outputs:
  Website:
    Description: The Public DNS for the EC2 Instance
    Value: !Sub "http://${JenkinsInstance.PublicDnsName}:8080"
